name: deploy to Github Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Explorando o Runner
        run: lsb_release -a && free -h

      - name: Setup pages
        uses: actions/configure-pages@v4

      - name: Verificar pasta src
        run: test -d src

      - name: Verificar arquivo CSS
        run: test -f src/css/style.css

      - name: Verificar footer com nome do aluno
        run: |
          grep -i "<footer>" src/index.html
          grep -i "Talita" src/index.html

      - name: Validar sintaxe do HTML
        uses: Cyb3r-Jak3/htmlhint-action@v1
        with:
          target_pattern: src/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Checar arquivos est치ticos
        run: |
          ls -R
          echo "Todos os arquivos foram carregados no runner!"

      - name: Auditoria final
        run: echo "O c칩digo do aluno Talita foi auditado, est치 seguindo as normas corretas e est치 pronto para o deploy!"
